// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PolyclinicInfrastructure.Persistence;

#nullable disable

namespace PolyclinicInfrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251206080955_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.ConsultationDerivation", b =>
                {
                    b.Property<Guid>("ConsultationDerivationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimeCDer")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentHeadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DerivationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.HasKey("ConsultationDerivationId");

                    b.HasIndex("DepartmentHeadId");

                    b.HasIndex("DerivationId");

                    b.HasIndex("PatientId");

                    b.HasIndex("DoctorId", "DerivationId", "DateTimeCDer")
                        .IsUnique();

                    b.ToTable("ConsultationDerivation", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.ConsultationReferral", b =>
                {
                    b.Property<Guid>("ConsultationReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimeCRem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentHeadId")
                        .HasColumnType("uuid");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferralId")
                        .HasColumnType("uuid");

                    b.HasKey("ConsultationReferralId");

                    b.HasIndex("DepartmentHeadId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ReferralId");

                    b.HasIndex("DoctorId", "ReferralId", "DateTimeCRem")
                        .IsUnique();

                    b.ToTable("ConsultationReferral", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Department", b =>
                {
                    b.Property<Guid>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.DepartmentHead", b =>
                {
                    b.Property<Guid>("DepartmentHeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.HasKey("DepartmentHeadId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("DoctorId");

                    b.ToTable("DepartmentHead", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Derivation", b =>
                {
                    b.Property<Guid>("DerivationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimeDer")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentFromId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentToId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.HasKey("DerivationId");

                    b.HasIndex("DepartmentToId");

                    b.HasIndex("PatientId");

                    b.HasIndex("DepartmentFromId", "DateTimeDer", "PatientId")
                        .IsUnique();

                    b.ToTable("Derivation", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.EmergencyRoom", b =>
                {
                    b.Property<Guid>("EmergencyRoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("GuardDate")
                        .HasColumnType("date");

                    b.HasKey("EmergencyRoomId");

                    b.HasIndex("DoctorId", "GuardDate")
                        .IsUnique();

                    b.ToTable("EmergencyRoom", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.EmergencyRoomCare", b =>
                {
                    b.Property<Guid>("EmergencyRoomCareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CareDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("EmergencyRoomId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.HasKey("EmergencyRoomCareId");

                    b.HasIndex("EmergencyRoomId");

                    b.HasIndex("PatientId");

                    b.HasIndex("CareDate", "PatientId")
                        .IsUnique();

                    b.ToTable("EmergencyRoomCare", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Employee", b =>
                {
                    b.Property<Guid>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("EmploymentStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Identification")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employee", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.ExternalMedicalPost", b =>
                {
                    b.Property<Guid>("ExternalMedicalPostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("ExternalMedicalPostId");

                    b.ToTable("ExternalMedicalPost", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Medication", b =>
                {
                    b.Property<Guid>("MedicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BatchNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CommercialCompany")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CommercialName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateOnly>("ExpirationDate")
                        .HasColumnType("date");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MaxQuantityNurse")
                        .HasColumnType("integer");

                    b.Property<int>("MaxQuantityWarehouse")
                        .HasColumnType("integer");

                    b.Property<int>("MinQuantityNurse")
                        .HasColumnType("integer");

                    b.Property<int>("MinQuantityWarehouse")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityNurse")
                        .HasColumnType("integer");

                    b.Property<int>("QuantityWarehouse")
                        .HasColumnType("integer");

                    b.Property<string>("ScientificName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("MedicationId");

                    b.ToTable("Medication", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.MedicationDerivation", b =>
                {
                    b.Property<Guid>("MedicationDerivationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultationDerivationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("MedicationDerivationId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("ConsultationDerivationId", "MedicationId")
                        .IsUnique();

                    b.ToTable("MedicationDerivation", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.MedicationEmergency", b =>
                {
                    b.Property<Guid>("MedicationEmergencyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmergencyRoomCareId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("MedicationEmergencyId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("EmergencyRoomCareId", "MedicationId")
                        .IsUnique();

                    b.ToTable("MedicationEmergency", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.MedicationReferral", b =>
                {
                    b.Property<Guid>("MedicationReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConsultationReferralId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("MedicationReferralId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("ConsultationReferralId", "MedicationId")
                        .IsUnique();

                    b.ToTable("MedicationReferral", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.MedicationRequest", b =>
                {
                    b.Property<Guid>("MedicationRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("WarehouseRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("MedicationRequestId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("WarehouseRequestId", "MedicationId")
                        .IsUnique();

                    b.ToTable("MedicationRequest", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Identification")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("PatientId");

                    b.HasIndex("Identification")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Patient", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Referral", b =>
                {
                    b.Property<Guid>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateTimeRem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentToId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExternalMedicalPostId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.HasKey("ReferralId");

                    b.HasIndex("DepartmentToId");

                    b.HasIndex("ExternalMedicalPostId");

                    b.HasIndex("PatientId", "DateTimeRem", "ExternalMedicalPostId")
                        .IsUnique();

                    b.ToTable("Referral", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.StockDepartment", b =>
                {
                    b.Property<Guid>("StockDepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MedicationId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("StockDepartmentId");

                    b.HasIndex("MedicationId");

                    b.HasIndex("DepartmentId", "MedicationId")
                        .IsUnique();

                    b.ToTable("StockDepartment", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("WarehouseId");

                    b.ToTable("Warehouse", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.WarehouseRequest", b =>
                {
                    b.Property<Guid>("WarehouseRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentHeadId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WarehouseManagerId")
                        .HasColumnType("uuid");

                    b.HasKey("WarehouseRequestId");

                    b.HasIndex("DepartmentHeadId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("WarehouseManagerId");

                    b.HasIndex("RequestDate", "DepartmentId")
                        .IsUnique();

                    b.ToTable("WarehouseRequest", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Doctor", b =>
                {
                    b.HasBaseType("PolyclinicDomain.Entities.Employee");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Doctor", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Nurse", b =>
                {
                    b.HasBaseType("PolyclinicDomain.Entities.Employee");

                    b.ToTable("Nurse", (string)null);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.WarehouseManager", b =>
                {
                    b.HasBaseType("PolyclinicDomain.Entities.Employee");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasIndex("WarehouseId")
                        .IsUnique();

                    b.ToTable("WarehouseManager", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.ConsultationDerivation", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.DepartmentHead", "DepartmentHead")
                        .WithMany("ConsultationDerivations")
                        .HasForeignKey("DepartmentHeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Derivation", "Derivation")
                        .WithMany("ConsultationDerivations")
                        .HasForeignKey("DerivationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Doctor", "Doctor")
                        .WithMany("ConsultationDerivations")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Patient", null)
                        .WithMany("ConsultationDerivations")
                        .HasForeignKey("PatientId");

                    b.Navigation("DepartmentHead");

                    b.Navigation("Derivation");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.ConsultationReferral", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.DepartmentHead", "DepartmentHead")
                        .WithMany("ConsultationReferrals")
                        .HasForeignKey("DepartmentHeadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Doctor", "Doctor")
                        .WithMany("ConsultationReferrals")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Patient", null)
                        .WithMany("ConsultationReferrals")
                        .HasForeignKey("PatientId");

                    b.HasOne("PolyclinicDomain.Entities.Referral", "Referral")
                        .WithMany("ConsultationReferrals")
                        .HasForeignKey("ReferralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepartmentHead");

                    b.Navigation("Doctor");

                    b.Navigation("Referral");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.DepartmentHead", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.Department", "Department")
                        .WithMany("DepartmentHeads")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Doctor", "Doctor")
                        .WithMany("DepartmentHeads")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Derivation", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.Department", "DepartmentFrom")
                        .WithMany("DerivationsFrom")
                        .HasForeignKey("DepartmentFromId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Department", "DepartmentTo")
                        .WithMany("DerivationsTo")
                        .HasForeignKey("DepartmentToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Patient", "Patient")
                        .WithMany("Derivations")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepartmentFrom");

                    b.Navigation("DepartmentTo");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.EmergencyRoom", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.Doctor", "Doctor")
                        .WithMany("EmergencyRooms")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.EmergencyRoomCare", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.EmergencyRoom", "EmergencyRoom")
                        .WithMany("EmergencyRoomCares")
                        .HasForeignKey("EmergencyRoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Patient", "Patient")
                        .WithMany("EmergencyRoomCares")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmergencyRoom");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Employee", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("PolyclinicDomain.Entities.Employee", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.MedicationDerivation", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.ConsultationDerivation", "ConsultationDerivation")
                        .WithMany("MedicationDerivations")
                        .HasForeignKey("ConsultationDerivationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Medication", "Medication")
                        .WithMany("MedicationDerivations")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConsultationDerivation");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.MedicationEmergency", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.EmergencyRoomCare", "EmergencyRoomCare")
                        .WithMany("MedicationEmergencies")
                        .HasForeignKey("EmergencyRoomCareId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Medication", "Medication")
                        .WithMany("MedicationEmergencies")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EmergencyRoomCare");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.MedicationReferral", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.ConsultationReferral", "ConsultationReferral")
                        .WithMany("MedicationReferrals")
                        .HasForeignKey("ConsultationReferralId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Medication", "Medication")
                        .WithMany("MedicationReferrals")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ConsultationReferral");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.MedicationRequest", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.Medication", "Medication")
                        .WithMany("MedicationRequests")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.WarehouseRequest", "WarehouseRequest")
                        .WithMany("MedicationRequests")
                        .HasForeignKey("WarehouseRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Medication");

                    b.Navigation("WarehouseRequest");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Patient", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithOne()
                        .HasForeignKey("PolyclinicDomain.Entities.Patient", "UserId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Referral", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.Department", "DepartmentTo")
                        .WithMany("Referrals")
                        .HasForeignKey("DepartmentToId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.ExternalMedicalPost", "ExternalMedicalPost")
                        .WithMany()
                        .HasForeignKey("ExternalMedicalPostId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Patient", "Patient")
                        .WithMany("Referrals")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DepartmentTo");

                    b.Navigation("ExternalMedicalPost");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.StockDepartment", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.Department", "Department")
                        .WithMany("StockDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Medication", "Medication")
                        .WithMany("StockDepartments")
                        .HasForeignKey("MedicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.WarehouseRequest", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.DepartmentHead", null)
                        .WithMany("WarehouseRequests")
                        .HasForeignKey("DepartmentHeadId");

                    b.HasOne("PolyclinicDomain.Entities.Department", "Department")
                        .WithMany("WarehouseRequests")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Warehouse", null)
                        .WithMany("WarehouseRequests")
                        .HasForeignKey("WarehouseId");

                    b.HasOne("PolyclinicDomain.Entities.WarehouseManager", "WarehouseManager")
                        .WithMany("WarehouseRequests")
                        .HasForeignKey("WarehouseManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("WarehouseManager");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Doctor", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.Department", "Department")
                        .WithMany("Doctors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("PolyclinicDomain.Entities.Doctor", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Nurse", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("PolyclinicDomain.Entities.Nurse", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.WarehouseManager", b =>
                {
                    b.HasOne("PolyclinicDomain.Entities.Employee", null)
                        .WithOne()
                        .HasForeignKey("PolyclinicDomain.Entities.WarehouseManager", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PolyclinicDomain.Entities.Warehouse", "Warehouse")
                        .WithOne("WarehouseManager")
                        .HasForeignKey("PolyclinicDomain.Entities.WarehouseManager", "WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.ConsultationDerivation", b =>
                {
                    b.Navigation("MedicationDerivations");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.ConsultationReferral", b =>
                {
                    b.Navigation("MedicationReferrals");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Department", b =>
                {
                    b.Navigation("DepartmentHeads");

                    b.Navigation("DerivationsFrom");

                    b.Navigation("DerivationsTo");

                    b.Navigation("Doctors");

                    b.Navigation("Referrals");

                    b.Navigation("StockDepartments");

                    b.Navigation("WarehouseRequests");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.DepartmentHead", b =>
                {
                    b.Navigation("ConsultationDerivations");

                    b.Navigation("ConsultationReferrals");

                    b.Navigation("WarehouseRequests");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Derivation", b =>
                {
                    b.Navigation("ConsultationDerivations");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.EmergencyRoom", b =>
                {
                    b.Navigation("EmergencyRoomCares");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.EmergencyRoomCare", b =>
                {
                    b.Navigation("MedicationEmergencies");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Medication", b =>
                {
                    b.Navigation("MedicationDerivations");

                    b.Navigation("MedicationEmergencies");

                    b.Navigation("MedicationReferrals");

                    b.Navigation("MedicationRequests");

                    b.Navigation("StockDepartments");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Patient", b =>
                {
                    b.Navigation("ConsultationDerivations");

                    b.Navigation("ConsultationReferrals");

                    b.Navigation("Derivations");

                    b.Navigation("EmergencyRoomCares");

                    b.Navigation("Referrals");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Referral", b =>
                {
                    b.Navigation("ConsultationReferrals");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Warehouse", b =>
                {
                    b.Navigation("WarehouseManager");

                    b.Navigation("WarehouseRequests");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.WarehouseRequest", b =>
                {
                    b.Navigation("MedicationRequests");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.Doctor", b =>
                {
                    b.Navigation("ConsultationDerivations");

                    b.Navigation("ConsultationReferrals");

                    b.Navigation("DepartmentHeads");

                    b.Navigation("EmergencyRooms");
                });

            modelBuilder.Entity("PolyclinicDomain.Entities.WarehouseManager", b =>
                {
                    b.Navigation("WarehouseRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
